---
- hosts: test
  tasks:
    - name: send request to monia server and expect 200 status code
      vars : 
        username : 'moeen.tavakoli'
        password : "12345"
      ansible.builtin.uri:
        url: http://192.168.50.36:8090/user/login
        method : POST
        body_format: json
        body:
          username : '{{ username }}'
          password : '{{ password }}'

          
