---
- hosts: test
  tasks:
    - name: send request to monia server and expect 200 status code
      vars : 
        token : 'TOKEN'
      ansible.builtin.uri:
        url: http://192.168.50.36:8090/user/info
        headers:
          Authorization: "{{token}}"
