---
  - hosts: localhost
    vars:
      template_name: sample_template
      index_alias_pattern: sample_index
   
    tasks:
      - ansible.builtin.uri:
          url: https://admin:admin@192.168.50.17:9200/_template/{{ template_name }}          
          method : PUT
          headers : 
            Content-Type: application/json
          body : "{{ lookup('template', '../json_files/create_template.j2') }}"
          validate_certs: no
          return_content : yes
          body_format : json