---
- hosts: test
  tasks:
    - name: remove directory in home directory
      file:
        path: /home/moeen.tavakoli/ansible-{{ item }}
        state: absent
      loop:
        - sample1
        - sample2
        - sample3