---
- hosts: test
  tasks:
    - name: create index 
      ansible.builtin.uri:
        url: https://admin:admin@192.168.50.17:9200/{{ lookup('ansible.builtin.ini', 'index_name', section='policy', file='ism.ini') }}
        method : PUT
        headers : 
          Content-Type: application/json
        body : "{{ lookup('ansible.builtin.file','create_index.json') }}"
        validate_certs: no
        return_content : yes
        body_format : json