---
- hosts: test
  tasks:
    - name: create policy 
      ansible.builtin.uri:
        url: https://admin:admin@192.168.50.17:9200/_plugins/_ism/policies/{{ lookup('ansible.builtin.ini', 'policy_name', section='policy', file='ism.ini') }}
        method : PUT
        headers : 
          Content-Type: application/json
        body : "{{ lookup('ansible.builtin.file','./json_files/create_policy.json') }}"
        validate_certs: no
        return_content : yes
        body_format : json
        status_code : 201


    - name: create template
      ansible.builtin.uri:
        url: https://admin:admin@192.168.50.17:9200/_template/{{ lookup('ansible.builtin.ini', 'template_name', section='policy', file='ism.ini') }}
        method : PUT
        headers : 
          Content-Type: application/json
        body : "{{ lookup('ansible.builtin.file','./json_files/create_template.json') }}"
        validate_certs: no
        return_content : yes
        body_format : json
    

    - name: create index 
      ansible.builtin.uri:
        url: https://admin:admin@192.168.50.17:9200/{{ lookup('ansible.builtin.ini', 'index_name', section='policy', file='ism.ini') }}
        method : PUT
        headers : 
          Content-Type: application/json
        body : "{{ lookup('ansible.builtin.file','./json_files/create_index.json') }}"
        validate_certs: no
        return_content : yes
        body_format : json