---
- hosts: test
  tasks:
    - name: create policy 
      ansible.builtin.uri:
        url: https://admin:admin@192.168.50.17:9200/_plugins/_ism/policies/{{ lookup('ansible.builtin.ini', 'policy_name', section='policy', file='ism.ini') }}
        method : PUT
        headers : 
          Content-Type: application/json
        body : "{{ lookup('ansible.builtin.file','create_policy.json') }}"
        validate_certs: no
        return_content : yes
        body_format : json