---
- hosts: test
  tasks:
    - name: remove files
      file:
        path: /home/moeen.tavakoli/ansible-{{ item }}
        state: absent
      loop:
        - sample1.txt
        - sample2
        - sample3
